packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - argon2
  - better-sqlite3
  - esbuild
  - sharp
allowBuilds:
  argon2: true
  better-sqlite3: true
  cpu-features: false
  esbuild: true
  sharp: true
  ssh2: false
